/* ************************************************************************

   qooxdoo - the new era of web development

   http://qooxdoo.org

   Copyright:
     2004-2007 by 1&1 Internet AG, Germany, http://www.1und1.de

   License:
     LGPL: http://www.gnu.org/licenses/lgpl.html
     EPL 1.0: http://www.eclipse.org/org/documents/epl-v10.php

   Authors:
     * Sebastian Werner (wpbasti)
     * Andreas Ecker (ecker)
     * Fabian Jakobs (fjakobs)

************************************************************************ */

/* ************************************************************************



************************************************************************ */

/*
WARNING: This file is generated by the gettext tools from ./source/translation/fr.po. Do not edit it by hand.
*/

qx.locale.Locale.define("vigigraph.translation.fr",
{
  "Last section": "Dernière section",
  "Service": "Service",
  "Graph end": "Fin du graphe",
  "Last 7 days": "7 derniers jours",
  "Timeframe": "Période",
  "Show graph": "Voir le graphe",
  "Show Nagios page": "Voir la page Nagios",
  "Next section": "Section suivante",
  "Last 3 months": "3 derniers mois",
  "Reload graph": "Recharger le graphe",
  "Search for a service (\"*\" for all, 100 max)": "Chercher un service (\"*\" pour tous, 100 maximum)",
  "Graph start": "Début du graphe",
  "Last 24 hours": "24 dernières heures",
  "Host:": "Hôte :",
  "Main Group": "Groupe principal",
  "Zoom out": "Dézoomer",
  "Host": "Hôte",
  "Last 48 hours": "48 dernières heures",
  "\"%1\" Graph for host %2": "Graphe \"%1\" pour l\'hôte %2",
  "Host Group": "Groupe d\'hôtes",
  "Host Picker": "Sélecteur d\'hôtes",
  "Search": "Chercher",
  "Timeframe menu": "Menu de choix de la période",
  "Zoom in": "Zoomer",
  "Reports": "Rapports",
  "Last 12 hours": "12 dernières heures",
  "Graph Group": "Groupe de graphes",
  "Last 14 days": "14 derniers jours",
  "Graph Name": "Graphe",
  "Service:": "Service :",
  "Host Name": "Hôte",
  "Search for a host (\"*\" for all, 100 max)": "Chercher un hôte (\"*\" pour tous, 100 maximum)",
  "Last year": "Dernière année",
  "Last 6 months": "6 derniers mois"
});